server:
    port: 8080  # The port on which the application will run.
    address: 0.0.0.0
    #    servlet:
    #        context-path: /api  # The base path for all endpoints in the application.
    error:
        include-message: always
logging:
    level:
        root: INFO
        com.nathanroos: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
    config:
        activate:
            on-profile: docker

#    datasource:
#            url: ${SPRING_DATASOURCE_URL}
#            username: ${SPRING_DATASOURCE_USERNAME}
#            password: ${SPRING_DATASOURCE_PASSWORD}
#            driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none   #use create to allow jpa to auto-generate from Entity classes; use none to use schema-h2.sql

    defer-datasource-initialization: true

    sql:
        init:
            platform: mysql
            mode: always
            schema-locations: classpath:schema.sql
            data-locations: classpath:data.sql