#services:
#  libraryapplication:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    hostname: libraryworker-service
#    ports:
#      - "8082:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      mysql1:
#        condition: service_healthy
#
#  mysql-libraryworker:
#    image: mysql:5.7
#    ports:
#      - "3307:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootpwd
#      - MYSQL_DATABASE=libraryworker-service
#      - MYSQL_USER=libraryworker-service
#      - MYSQL_PASSWORD=pwd
#    volumes:
#      - ./data/mysql1:/var/lib/mysql1
#      - ./data/init.d:/docker-entrypoint-initdb.d
#    healthcheck:
#      test:
#        [
#          "CMD",
#          "mysqladmin",
#          "ping",
#          "-uuser",
#          "-ppwd",
#          "-h",
#          "localhost",
#        ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#
#  phpmyadmin:
#    image: phpmyadmin:5.2.0
#    container_name: libraryworker-service
#    links:
#      - mysql1
#    restart: always
#    ports:
#      - 5015:80
#    environment:
#      - PMA_ARBITRARY=1